version: "3"

services:
  depot:
    build: .
    ports:
      - "3030:3000"
    volumes:
      - .:/usr/src/app
      - gem_cache:/gems
    env_file:
      - .env/development/database
      - .env/development/web

  mysql:
    image: mysql:5.7
    restart: always
    env_file:
      - .env/development/database
    volumes:
      - development_db:/var/lib/mysql

  mysql_test:
    image: mysql:5.7
    restart: always
    env_file:
      - .env/test/database
    volumes:
      - test_db:/var/lib/mysql

  mysql_prod:
    image: mysql:5.7
    restart: always
    env_file:
      - .env/production/database
    volumes:
      - production_db:/var/lib/mysql

volumes:
  gem_cache:
  development_db:
  production_db:
  test_db:
